sylius_resource:
    resources:
        ############## OFFICE ##############
        app.office:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Office
                repository: App\Repository\OfficeRepository
                form : App\Form\OfficeType
        
        ############## Licence ##############
        app.licence:
            driver: doctrine/orm
            classes:
                model: App\Entity\Licence\Licence
                repository: App\Repository\LicenceRepository
                form : App\Form\LicenceType