sylius_resource:
    resources:
        ############## OFFICE ##############
        app.office:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Office
                repository: App\Repository\OfficeRepository
                form : App\Form\OfficeType
        
        ############## Licence ##############
        app.licence:
            driver: doctrine/orm
            classes:
                model: App\Entity\Licence\Licence
                repository: App\Repository\LicenceRepository
                form : App\Form\LicenceType

        ############## Subscription ##############
        app.subscription:
            driver: doctrine/orm
            classes:
                model: App\Entity\Subscription\Subscription
                repository: App\Repository\SubscriptionRepository
                # form : App\Form\SubscriptionType

        ############## Subscription Payment SCHEDULE ##############
        app.subscription_payment_schedule:
            driver: doctrine/orm
            classes:
                model: App\Entity\SubscriptionPaymentSchedule\SubscriptionPaymentSchedule
                repository: App\Repository\SubscriptionRepository