sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

################## Office ##################
### GRID ###
app_admin_office:
    resource: |
        alias: app.office
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_office
        vars:
            all:
                subheader: app.ui.office
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin
### CREATE OFFICE ###
app_admin_office_create:
    path: /admin/create/office
    defaults:
        _controller: App\Controller\OfficeController::create
        _sylius:
            section: admin
            template: "@App/templates/office/index.html.twig"
            permission: true


################## Licence ##################
### GRID ###
app_admin_licence:
    resource: |
        alias: app.licence
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: app_admin_licence
        vars:
            all:
                subheader: app.ui.licence
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin
### CREATE LICENCE ###
app_admin_licence_create:
    path: /admin/create/licence
    defaults:
        _controller: App\Controller\LicenceController::create
        _sylius:
            section: admin
            # template: "@App/templates/office/index.html.twig"
            permission: true
### UPDATE LICENCE ###
app_admin_licence_update:
    path: /admin/licences/{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: App\Controller\LicenceController::update
        _sylius:
            section: admin
            permission: true
    requirements:
        id: \d+

# AJAX QUERY FOR FIELD SELECT DROPDOWN
app_admin_ajax_order_by_name_phrase:
    path: /admin/order/search
    methods: [GET]
    defaults:
        _controller: App\Controller\LicenceController::getLicenceCodeCrm
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: $phrase
                    limit: 5

################## Subscription ##################
### GRID ###
app_admin_subscription:
    resource: |
        alias: app.subscription
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_subscription
        vars:
            all:
                subheader: app.ui.subscription
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin
### SHOW SUBSCRIPTION ###
app_admin_subscription_show:
    path: /admin/subscriptions/{id}
    methods: [GET]    
    defaults:
        _controller: App\Controller\SubscriptionController::show
        _sylius:
            section: admin
            # template: "@App/templates/office/index.html.twig"
            permission: true
    requirements:
        id: \d+

### UPDATE SUBSCRIPTION EXTENSION ###
update_subscription_extended:
    path: '/subscription/{id}/update-extended'
    methods: ['POST', 'PUT']
    defaults:
        _controller: App\Controller\SubscriptionController::updateExtended
        _sylius:
            section: admin
            permission: true
    requirements:
        id: \d+

### STATES TRANSITIONS ###
transition_subscription_pause:
    path: /admin/subscriptions/{id}/pause
    methods: [PUT]
    defaults:
        _controller: App\Controller\SubscriptionController::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: subscription_manual
                transition: pause
            redirect: referer

transition_subscription_cancel:
    path: /admin/subscriptions/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: App\Controller\SubscriptionController::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: subscription_manual
                transition: cancel
            redirect: referer

transition_subscription_activate:
    path: /admin/subscriptions/{id}/activate
    methods: [PUT]
    defaults:
        _controller: App\Controller\SubscriptionController::applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: subscription_manual
                transition: activate
            redirect: referer
